name: Test

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, bundle, build, deploy, and test
      env:
        CI: true
        GH_TOKEN: ${{ secrets.NOT_A_SECRET }}
      run: |
        npm ci
        npm test
        npm run bundle --if-present
        npm run build-storybook
        npm run deploy-storybook -- --ci


